name: Docker Image CI

on: 
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 构建 Docker 镜像
      run: docker build . --file Dockerfile --tag 350037310/ng-better:v_0.0.1

    - uses: manusa/actions-publish-docker@master
    - name: 上传 Docker 镜像至 DockerHub
      with: 
        name: 350037310/ng-better
        username: 350037310
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
