name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 构建 Docker 镜像
      run: docker build . --file Dockerfile --tag 350037310/ng-better:v_0.0.1
    
    - name: 上传 Docker 镜像至 DockerHub
    - uses: manusa/actions-publish-docker@master
      with: 
        name: 350037310/ng-better
        username: 350037310
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
